services:
  db:
    image: postgres:16-alpine
    container_name: rest-api-postgres
    environment:
      POSTGRES_DB: restApiDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d restApiDB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: rest-api-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restApiDB
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: "1234"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
